"""Shared banner for every rendered file.

Deliberately free of timestamps and hostnames so rendering is
byte-reproducible for a given config.
"""

GENERATED_HEADER = (
    "# Generated by the fwOS config engine from /etc/project/config.yaml"
    " (schema v1).\n"
    "# Do not edit; changes will be overwritten."
    " Edit the config and run `fwctl apply`.\n"
)
